# -*- coding: utf-8 -*-
"""derivative-i1pynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/HASTIAMIRI5/6b327ed53437c0eb63d02fffef80ac2d/derivative-i1pynb.ipynb

Derivative-Gradient-Chain Rule
"""

def get_derivative(func, x):

  h = 0.0001
  return (func(x+h) - func(x)) / h

def f(x):
  return x**2

x = 3
computed = get_derivative(f , x)
actual = 2*x
print(computed ,actual )

!pip install sympy

import sympy as sym

x = sym.Symbol('x')

sym.diff(x**5)